### PR TITLE
Pr 17 rules page info updates

### PR DESCRIPTION
**Pull request by PrettyCoolPattern**
Consolidation of discord and website rules, Added formatting & clarity to Game Modification Rules

### CODE REVIEW

**Comment by slassen** [comment]
I think I'd rather have the helpful install links under everything else and can axe the "!under construction!" stuff. I think it's fair our users assume there will be content changes, especially with the site being nearly from scratch.

**Comment by PrettyCoolPattern** [comment]
slassen, pretty sure you're commenting on install page, under rules PR. I believe I sent the updated changes to the 16-PR-Install-Page branch with your requested updates.  🤠

**Comment by slassen** [comment]
Awesome, thanks. Will get to that one first.

**Comment by slassen** [comment]
Seems like I commented about the install page because this an install conflict on it. Could you verify this is what you wanted changed on this PR?

**Pull request closed without merging**
