### PR TITLE
Wrap the content shown about players for small screens

### PR DESCRIPTION
**Pull request by InoUno**
Before:
image

After
image

### CODE REVIEW

**Comment by slassen** [comment]
What about centering it with auto margin of under a maxWidth? One component per “line”.

**Comment by InoUno** [comment]
I tried with column flex-direction initially, but thought it looked like it was wasting a bit too much space:
image

I'm fine with changing it to that though, since it does look more consistent.

**Comment by bkesecker** [comment]
Jobs and Crafts collapsible like Auction House and Bazaar?

**Comment by slassen** [comment]
Yeah Cygon, it's probably a good idea for us to examine a good solution for mobile on this. Maybe a designer can pop in with a good idea sometime.

**Pull request merged**
