### PR TITLE
Online indicator in bazaar, limit bazaar search to 300 items

### LINKED ISSUE #100: Generating only online bazaars
The bazaar functionality is great on the website, but I would love to see it only generator online bazaars within the database. Often when I'm searching for an item, I'll find something around the price I'm looking for it to be on a character that's offline or worse offline and hasn't logged into the server for an extended period if time.

### PR DESCRIPTION
**Pull request by rude-jerk**
image

Resolves https://github.com/EdenServer/eden-web/issues/100

### CODE REVIEW

**Comment by rude-jerk** [comment]
Actually, I hated the previous implementation - updated:
image

**Comment by bkesecker** [comment]
Loaded to test server, but not seeing the 'Show Offline' button.  Maybe because there are no players online?  http://test.edenxi.org:8080/tools/item/fire_staff

**Comment by rude-jerk** [comment]
This change doesn't appear to be loaded on the test server - item.jsx looks unchanged in the browser debugger at that url.

**Comment by bkesecker** [comment]
Yep.  Forgot to switch branches before building.  Test server is updated.

**Comment by InoUno** [comment]
At least personally, I like to be able to see all bazaars, both online and offline, without having to click on a button. So I think I preferred the previous design, if anything.

**Comment by rude-jerk** [comment]
image

Reverting to this certainly works for me if we agree that it's a better solution.
My thoughts on the change were mostly around the assumption that the reason people check bazaars is to buy something _now_, so the filter to online players only would decrease the response size - however, in thinking about it it would be a response increase in the event that you want to see both online and offline bazaars since you'd be sending two separate requests.

**Comment by bkesecker** [comment]
> the reason people check bazaars is to buy something now

True, if you have lots of gil and don't care, but for those looking for a bargain?

**Comment by rude-jerk** [comment]
Agreed that those people exist (those willing to wait and hunt for a bargain) - removing the online filter for that is available. It sounds like simply displaying online or not in the list and not applying any sort of filter is an agreeable option, though! 

I'll revert my branch to that version.

Does anyone have any issues with limiting bazaar return results to 300 and sorting on ONLINE, PRICE, CHARNAME ASC?

**Comment by bkesecker** [comment]
No opinion here on the limit, but know that there are about 40,000 characters in the database, with a maximum of 65,535.  Sorting by online status, and then by price ascending would be my preference.  The likelihood of needing by name is slim, but certainly won't hurt.

**Comment by rude-jerk** [comment]
Current state sorts online, price, charname. I reverted back to the online/offline indicator. Let me know if there are any other issues.


Thanks!

**Comment by bkesecker** [comment]
Working in test.

image

http://test.edenxi.org:8080/tools/item/chunk_of_white_steel

**Review by bkesecker — APPROVED** [review]

**Pull request merged**
