### PR TITLE
PR-10 through PR-15

### PR DESCRIPTION
**Pull request by InoUno**
Should be merged after #35. This PR will probably need to have master merged into it, once #35 has been merged.

* #24: Make Install page responsive on various screen sizes.
* #25: Make Rules page responsive on various screen sizes.
* #26: Add InfoDisplay component to reduce repetition of code with Cards being used across site, and also for design consistency.
* #27: Make contributing tabs functional. Apologies for styling changes due to using bootstrap.
* #28: Implement the InfoDisplay component into the Install page for consistency and to reduce code repetition.
* #29: Make links page responsive.

### CODE REVIEW

**Comment by slassen** [comment]
More merge conflicts unfortunately.

**Comment by InoUno** [comment]
Pushed a fix for the merge conflict.

**Comment by danielvarcas** [comment]
@slassen sure I will take a look at this tomorrow :)

**Comment by danielvarcas** [comment]
@slassen This is all done now :slightly_smiling_face: 

With the link cards, I'm thinking of putting a button on them which is only displayed on phone/tablet screen sizes. This will help make it obvious that the cards are links in absence of the hover animations (which won't occur when using touch screen controls). I'll do this in a separate branch/PR though and you can let me know what you think of it.

Also I'd like to revisit the FAQs page (and likely all the pages at some point) as there are things I can do to make it look a little less boring while still keeping it minimal.

Thanks! :smile:

**Pull request merged**
