### PR TITLE
PR-6: links props

### PR DESCRIPTION
**Pull request by danielvarcas**
Validate Links props and only pass necessary props.

### CODE REVIEW

**Comment by danielvarcas** [comment]
Hi @slassen . Yes this is probably a clash with Bootstrap, I hadn't noticed that. However I actually did some styling on this page at later commits, which is part of `PR-15-responsive-links-page`.

It might be easier if once those commits are merged in, you can give me feedback on whether you want me to change anything about the cards/links, as they look a bit different to the current ones. I can make any changes first thing Saturday morning.

Also just as a sidenote, I appreciate the site is starting to look very standard bootstrappy, which might not be what you want. We talked about this recently and I'd like to look at implementing theme customisation this weekend, so we can get it looking how you imagine it a lot easier.

**Comment by danielvarcas** [comment]
Also I'm sure you've seen @InoUno 's PR's now were my PRs are bundled together, but if not it might be easier to leave this one and look at those two instead. I'll close these PRs if/when the bundled PRs are merged in.

**Comment by slassen** [comment]
I’m not too crazy about how things are styled because it’s a weak point of mine. I just try to keep things minimal. So as long as it’s presentable you and/or any designer aren’t going to butt heads with me. As long as it’s within reason. :)

Sounds good, I will probably look at the big PRs first and hopefully that handles the big file touches in PRs

**Comment by danielvarcas** [comment]
@slassen Ok got you :) The two bundles PRs which Ino did will make these individual ones obsolete, so if you decide to just look at and accept those two, then these smaller PRs can be abandoned.

**Pull request closed without merging**
