### PR TITLE
Fixed variable to read proper default on whose online

### PR DESCRIPTION
**Pull request by JasonHoku**
Didn't have time to set up a test environment with the tools database and properly confirm this was the fix but checks passed and the logic is sound.

### CODE REVIEW

**Comment by InoUno** [comment]
This is not correct.
It should stay as it is, with the `perPage` variable being passed to the component, since that variable is initialized to `perPageDefault` and can be changed.

**Comment by JasonHoku** [comment]
Bah, I don't understand why it loads 100 as default then. I'll have to set up my test server and poke around more soon. 
client\src\components\pagination\index.jsx:

  perPageDefault = 10,
   const [perPage, setPerPage] = React.useState(perPageDefault);
       defaultValue={perPageDefault}

**Comment by InoUno** [comment]
It loads 100 as default, because that's what it's currently set to:
https://github.com/EdenServer/eden-web/blob/e9bad09c9832201654bbc379cf882032d549df16/client/src/components/tools/OnlineList.jsx#L92

**Comment by JasonHoku** [comment]
> It loads 100 as default, because that's what it's currently set to:
> https://github.com/EdenServer/eden-web/blob/e9bad09c9832201654bbc379cf882032d549df16/client/src/components/tools/OnlineList.jsx#L92

Oh! I understand now, I was definitely poking at the wrong component. I'll update this pr immediately.

**Comment by InoUno** [comment]
It also looks like it needs to be set in a more centralized place in that file, since it's not connected to how many are actually fetched initially: 
https://github.com/EdenServer/eden-web/blob/e9bad09c9832201654bbc379cf882032d549df16/client/src/components/tools/OnlineList.jsx#L72

**Comment by JasonHoku** [comment]
Alright, I have reflected that in this PR as well, good eye Ino.

**Review by bkesecker — APPROVED** [review]

**Pull request merged**
