### PR TITLE
Add initial SQL files and database setup guide

### PR DESCRIPTION
**Pull request by InoUno**
Added SQL files to create the necessary tables for the website. The table dumps are currently taken from DSP/topaz, and then modified to fit the eden-specific queries that are currently in the webserver. Having the actual Eden DB schema here instead would be great!

Also added a database setup guide to the README, and a few SQL scripts to make it easier to add test content to the website.

### CODE REVIEW

**Comment by slassen** [comment]
Since DSP is deprecated now it's safe to assume it's not going to update its tables. So I'd prefer having players set up DSP on their own and then having a single script to modify or add additional tables in this repo. Perhaps even having some seeds for a demo. But let me ponder on this one for a bit. Would like to hear your thoughts.

**Comment by InoUno** [comment]
I think it's best to have the all of the necessary SQL setup as a part of this repository, such that it can be a standalone entity, instead of relying on DSP and it's wiki always being available for players/devs to go to.

Also, I'm planning on setting up tests for the server-side code, which will validate that the queries etc. work as intended, and that would not be possible if it doesn't know how to create the necessary tables and data.

**Comment by slassen** [comment]
I merged in someone else's PR and it caused a conflict here. Maybe in the future we can slim these files down but I'll merge them in for now after that conflict is resolved.

**Comment by InoUno** [comment]
Conflict fixed. Yeah, I'm considering moving most/all of the data entries to have smaller files and faster database setup, and just leave in enough for testing.

**Pull request merged**
