### PR TITLE
Limit Character Searches to Normal Status

### PR DESCRIPTION
**Pull request by bkesecker**
New character status hidden (5).  This was necessary to hide a vulgar representation of an existing player's character name.  Perhaps a better alternative is to omit banned, suspended, and inactive accounts from the search.  If so, status = 1 will do that.

### CODE REVIEW

**Comment by bkesecker** [comment]
> Searching for "godmode" locally crashed the server. Detailed error included.

No crash with the same code and search term on test, but I did notice searching for "godmode" returned results, but then "godm", "godmo", "godmod" did not pick up the change in search term and the results didn't change.

**Comment by slassen** [comment]
It’s probably because you don’t have the same character data locally. Try searching for a character that returns a character in a status like godmode does on prod.

**Comment by bkesecker** [comment]
Hmm.  Test has a copy of production characters.  Do you have the error details?

**Comment by bkesecker** [comment]
I do get this error in the browser debugger if no results are returned.

> playersearch.jsx:44 Uncaught (in promise) TypeError: Cannot read property 'total' of null
>    at playersearch.jsx:44
>    at apiUtil.js:15

**Comment by slassen** [comment]
I’ll take a screenshot when I get near my computer next.

**Comment by slassen** [comment]
Screenshot (6)
I inspected what's coming from on of the api calls and it could be because the total is showing a count but it's outside of the range of the array. So my guess is there is probably one or more queries to update for this.

**Comment by bkesecker** [comment]
Need to figure out why status = 1 causes above failure.

**Comment by InoUno** [comment]
Pushed what I think should fix the issue you're seeing.
The problem was a mismatch between the where clauses in the two queries that is performed on a character search.

**Comment by slassen** [comment]
Status is on the accounts table. Will need a join.

**Comment by InoUno** [comment]
Ah, you are right. Didn't test that properly.

**Pull request merged**
