### PR TITLE
Front-end router change, add navbar and footer

### PR DESCRIPTION
**Pull request by danielvarcas**
- Replace react-router with @reach-router
- Add a responsive site navbar
- Add a site footer

In terms of changing the router package, this is potentially a more controversial PR. There are reasons for it however. I initially started looking into doing this because putting links in the navbar outside of the `<Router>` block was proving to be not very straight-forward. `@reach/router` is less complex and lets you put `<Link>`s anywhere. It also requires less code than `react-router`.

`react-router` and `@reach/router` are currently in the process of becoming one package, with `react-router` being the surviving package, but with the result that it ends up looking a lot more like `@reach/router`. After reading `react-router`'s [article about this](https://reacttraining.com/blog/reach-react-router-future/), considering ease of migration in the future, plus ease of use for now, I think it makes sense to use `@reach/router` now. When the packages are merged, switching back to the _new_ `react-router` should be very simple to do (the article says it can be done "in an afternoon").

Ultimately, I have found `@reach/router` much simpler to use. I've gone through each page and the tools and they all seem to work fine still. Please let me know what you think of this change and if you have any strong opinions about staying with `react-router`, do let me know.

I also have added a responsive navbar. This replaces the hamburger menu.

Because we needed somewhere to put the FFXI trademark/copyright info, I've also added a footer (which took me a surprisingly long time to figure out how to position properly...).

I appreciate this is quite a large PR and apologies that a lot of the changes will be formatting. Any questions let me know. Thanks!

### CODE REVIEW

**Comment by danielvarcas** [comment]
Sorry, there was an issue on initial load with `npm start` sending you to `/public`, which did not exist. Then the `/home` redirect from `/` was causing an error while trying to set state (think it was happening too fast). So set home path to `/` and removed redirection.

I then noticed some issues with padding/margins on various pages. There is a dark background behind the main content now (this is so the footer looks like it goes to the bottom of the page). The nav was looking bigger than it is because the padding on some pages was revealing the dark background at the top of the page. So did some work going through each page getting the padding/margins working properly.

Also did some minor layout tweaks the the homepage (eventually want to get all InfoDisplays/Cards looking similar with title in header).

Thanks.

**Comment by danielvarcas** [comment]
@InoUno did some work to improve the footer positioning, so that it's not taking up excess space on the page if the page doesn't have much content (i.e. tools, home). I've merged that into this PR.

**Comment by slassen** [comment]
Unfortunately the prettier PR caused merge conflicts here.

**Comment by danielvarcas** [comment]
Ok I'll try to look at this today

**Comment by danielvarcas** [comment]
@slassen Conflicts now resolved

**Comment by slassen** [comment]
Yeah this does change the UX quite a bit but like I said, I'm ok with it. I only have two suggestions here.

1. The header looks to have too much padding. When I looked at the inspector it was because the name badge was thick. In this case I would probably get rid of it. (The Eden white thing.)
2. You don't need to update this if it looks bad after you try it but to me the footer also looks too large for most desktop views but perfect for mobile view to stack. Can you play around with some CSS like this for views over a certain width like desktop views? I'm not versed in Bootstrap so there may be props you can change instead of CSS.

```css
display: flex;
align-items: center;
justify-content: space-around;
padding: 0 !important;
```

**Comment by danielvarcas** [comment]
@slassen yes I can certainly look into those. I noticed the EDEN logo text was too large height wise but couldn't understand why. I will look into it again. And the footer change will be easy to do.

**Comment by slassen** [comment]
No problem. Easy to just axe the logo lol

**Comment by danielvarcas** [comment]
@slassen This is all sorted now :) Let me know what you think

**Comment by slassen** [comment]
@danielvarcas I didn't realize to try a production build before I merged this but production builds are breaking on this PR and now in `master` after this PR. I think it has to do with `/public` in `package.json` but I haven't dug into it.

**Comment by danielvarcas** [comment]
> I'm not really a fan of both that plus a home button that does the same thing. As well as the nav links being along side it. Although I'm going to approve this and leave it up to you if you think it could use some additional changes in a future PR.

Hi @slassen . Sorry I didn't catch these comments at the time. Easy to get rid of the home link, I can do that. About the nav links, do you mean that you don't like those being right next to the logo? I could align them to the right to separate them from the logo if that helps.

**Comment by slassen** [comment]
Just personal preference on the alignment. But the two buttons that do the same would be nice to remedy.

**Pull request merged**
