### PR TITLE
Make news appear first on the home page, when on mobile

### PR DESCRIPTION
**Pull request by InoUno**

### CODE REVIEW

**Comment by slassen** [comment]
I think we can actually just get rid of yells on mobile on the news page. Since it has its own tab now.

**Comment by InoUno** [comment]
Want to keep the yell box on desktop, but not show it for smaller screens?
If we need to make that distinction, I think we need to use something like [react-responsive](https://github.com/contra/react-responsive) to determine what to render, and what not to render.

**Comment by InoUno** [comment]
Or I guess we could also just do `display: none` with a CSS media query, but that doesn't seem like the nicest solution.

**Comment by slassen** [comment]
Either one of those solutions should work. With the first being faster but I don’t think either will be a bad choice.

**Pull request merged**
