### PR TITLE
Added dark mode

### LINKED ISSUE #112: Feature Request: Add Dark Mode Option
Current website layout is very light and bright, a dark mode option would help to reduce strain on the eyes.

### PR DESCRIPTION
**Pull request by ejedev**
This PR implements a fairly simple light/dark toggle to the Eden website. It uses local storage to store a 'theme' and defaults to light if it is not present. This shouldn't change how the light/default site looks. The toggle itself was added as a link. I modified the Link/navlink section to allow items labelled as functions to be passed in with a function of their own. On click the function is executed and the event is passed so that the routing can be ignored if desired.

Darkmode was accomplished by using the [Darkly theme from Bootswatch.](https://bootswatch.com/darkly/) Some adaptations needed to be made to make it work. 

The client also uses Semantic UI from `semantic-ui-react`. Unfortunately, that package does not natively allow theming. Multiple other packages are needed for it to work. I didn't want to add dependencies to a project I don't have a lot of experience with so I opted to add a section of vanilla css linked to `body.dark` to accomplish the same thing. I am open to changing this though.

Resolves #112

### CODE REVIEW

**Comment by InoUno** [comment]
The darkly theme seems to alter more things than just the colors, which leads to a shift in sizing/spacing when toggling. It could end up making some things looks nice in one of the themes but not the other.

Have you looked at stuff like [bootstrap-dark](https://github.com/ForEvolve/bootstrap-dark), that says it just does colors?

**Comment by ejedev** [comment]
> The darkly theme seems to alter more things than just the colors, which leads to a shift in sizing/spacing when toggling. It could end up making some things looks nice in one of the themes but not the other.
> 
> Have you looked at stuff like [bootstrap-dark](https://github.com/ForEvolve/bootstrap-dark), that says it just does colors?

I did notice a change in some sizing aspects so it would definitely be good to avoid that. It looked good on my end but I realize that it will most likely be different for other sized monitors/displays and could make the experience worse. Will do some tests with the new theme.

**Comment by ejedev** [comment]
New commit removes the darkmode styling from `style.css` and instead puts it in a new `theme-switch.scss` file. This should allow for easier modficiations of the theme or setting up new themes in the future.

It also removes the usage of `darkly`. I didn't find a good premade dark theme that didn't also alter the styling/sizing of the site significantly so I made this simple stylesheet instead.

**Review by InoUno — APPROVED** [review]
I think that works quite well, thanks!

**Pull request merged**
